# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nakshatra_pb2 as nakshatra__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nakshatra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NakshatraStub:
    """v0.1 service surface. See docs/v0.1-implementation-plan.md §3.5 for the
    full rationale; in short:
    - Info: capability handshake at session start (model id, layer range, headroom)
    - Forward: stateless single forward pass over the worker's layers (testing aid)
    - Inference: stateful bidirectional stream, one per session_id

    Wire dtype is fp16 by default. Activation transport is always full-precision;
    no on-wire quantization in v0.1.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/nakshatra.v0_1.Nakshatra/Info',
                request_serializer=nakshatra__pb2.InfoRequest.SerializeToString,
                response_deserializer=nakshatra__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/nakshatra.v0_1.Nakshatra/Forward',
                request_serializer=nakshatra__pb2.ForwardRequest.SerializeToString,
                response_deserializer=nakshatra__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.Inference = channel.stream_stream(
                '/nakshatra.v0_1.Nakshatra/Inference',
                request_serializer=nakshatra__pb2.InferenceStep.SerializeToString,
                response_deserializer=nakshatra__pb2.InferenceStep.FromString,
                _registered_method=True)
        self.TruncateKV = channel.unary_unary(
                '/nakshatra.v0_1.Nakshatra/TruncateKV',
                request_serializer=nakshatra__pb2.TruncateRequest.SerializeToString,
                response_deserializer=nakshatra__pb2.TruncateResponse.FromString,
                _registered_method=True)
        self.Sleep = channel.unary_unary(
                '/nakshatra.v0_1.Nakshatra/Sleep',
                request_serializer=nakshatra__pb2.SleepRequest.SerializeToString,
                response_deserializer=nakshatra__pb2.SleepResponse.FromString,
                _registered_method=True)
        self.Wake = channel.unary_unary(
                '/nakshatra.v0_1.Nakshatra/Wake',
                request_serializer=nakshatra__pb2.WakeRequest.SerializeToString,
                response_deserializer=nakshatra__pb2.WakeResponse.FromString,
                _registered_method=True)


class NakshatraServicer:
    """v0.1 service surface. See docs/v0.1-implementation-plan.md §3.5 for the
    full rationale; in short:
    - Info: capability handshake at session start (model id, layer range, headroom)
    - Forward: stateless single forward pass over the worker's layers (testing aid)
    - Inference: stateful bidirectional stream, one per session_id

    Wire dtype is fp16 by default. Activation transport is always full-precision;
    no on-wire quantization in v0.1.

    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inference(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TruncateKV(self, request, context):
        """Speculative decoding (slice 1): discard a rejected speculative tail from this
        worker's KV. The coordinator fans this out to EVERY worker after accept().
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sleep(self, request, context):
        """2026-06-21 sleep-mode: release/re-acquire the GPU without a process respawn.
        Sleep frees the daemon's ctx+model weights (keeps the process + ROCm backend
        resident); Wake reloads from the warm page cache (~440ms vs ~7.5s cold).
        Additive — older workers simply don't implement these; the lifecycle probes
        protocol_capabilities ("sleep_wake") before using them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Wake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NakshatraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=nakshatra__pb2.InfoRequest.FromString,
                    response_serializer=nakshatra__pb2.InfoResponse.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=nakshatra__pb2.ForwardRequest.FromString,
                    response_serializer=nakshatra__pb2.ForwardResponse.SerializeToString,
            ),
            'Inference': grpc.stream_stream_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=nakshatra__pb2.InferenceStep.FromString,
                    response_serializer=nakshatra__pb2.InferenceStep.SerializeToString,
            ),
            'TruncateKV': grpc.unary_unary_rpc_method_handler(
                    servicer.TruncateKV,
                    request_deserializer=nakshatra__pb2.TruncateRequest.FromString,
                    response_serializer=nakshatra__pb2.TruncateResponse.SerializeToString,
            ),
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=nakshatra__pb2.SleepRequest.FromString,
                    response_serializer=nakshatra__pb2.SleepResponse.SerializeToString,
            ),
            'Wake': grpc.unary_unary_rpc_method_handler(
                    servicer.Wake,
                    request_deserializer=nakshatra__pb2.WakeRequest.FromString,
                    response_serializer=nakshatra__pb2.WakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nakshatra.v0_1.Nakshatra', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nakshatra.v0_1.Nakshatra', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Nakshatra:
    """v0.1 service surface. See docs/v0.1-implementation-plan.md §3.5 for the
    full rationale; in short:
    - Info: capability handshake at session start (model id, layer range, headroom)
    - Forward: stateless single forward pass over the worker's layers (testing aid)
    - Inference: stateful bidirectional stream, one per session_id

    Wire dtype is fp16 by default. Activation transport is always full-precision;
    no on-wire quantization in v0.1.

    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakshatra.v0_1.Nakshatra/Info',
            nakshatra__pb2.InfoRequest.SerializeToString,
            nakshatra__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakshatra.v0_1.Nakshatra/Forward',
            nakshatra__pb2.ForwardRequest.SerializeToString,
            nakshatra__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nakshatra.v0_1.Nakshatra/Inference',
            nakshatra__pb2.InferenceStep.SerializeToString,
            nakshatra__pb2.InferenceStep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TruncateKV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakshatra.v0_1.Nakshatra/TruncateKV',
            nakshatra__pb2.TruncateRequest.SerializeToString,
            nakshatra__pb2.TruncateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakshatra.v0_1.Nakshatra/Sleep',
            nakshatra__pb2.SleepRequest.SerializeToString,
            nakshatra__pb2.SleepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Wake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakshatra.v0_1.Nakshatra/Wake',
            nakshatra__pb2.WakeRequest.SerializeToString,
            nakshatra__pb2.WakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
